sudo: required
services:
  - docker

before_install:
  - docker build -t mightcontainer002/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true mightcontainer002/react-test npm test

after_success:
  - docker build -t mightcontainer002/multi-client ./client
  - docker build -t mightcontainer002/multi-nginx ./nginx
  - docker build -t mightcontainer002/multi-server ./server
  - docker build -t mightcontainer002/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take these images and push them to dockerhub
  - docker push mightcontainer002/multi-client
  - docker push mightcontainer002/multi-nginx
  - docker push mightcontainer002/multi-server
  - docker push mightcontainer002/multi-worker

#deploy:
#  edge: true
#  provider: elasticbeanstalk
#  region: "us-west-2"
#  app: "docker-react"
#  env: "DockerReact-env"
#  bucket_name: "elasticbeanstalk-us-west-2-904575555207"
#  bucket_path: "docker-react"
#  on:
#    branch: master
#  access_key_id: $AWS_ACCESS_KEY
#  secret_access_key: $AWS_SECRET_KEY





